name: Deploy Shiny app to shinyapps.io

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      # 1. Check out your code
      - uses: actions/checkout@v3

      # 2. Install R 4.4.4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.4.4

      # 3. Install dependencies
      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c(
            "rsconnect","shiny","httr","jsonlite",
            "dplyr","text2vec","glmnet","stringdist"
          ))'

      # 4. Deploy to shinyapps.io
      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript -e '
            rsconnect::setAccountInfo(
              name   = Sys.getenv("SHINYAPPS_NAME"),
              token  = Sys.getenv("SHINYAPPS_TOKEN"),
              secret = Sys.getenv("SHINYAPPS_SECRET")
            );
            rsconnect::deployApp(
              appName       = Sys.getenv("SHINYAPPS_NAME"),
              appDir        = ".",
              appPrimaryDoc = "app.R"
            )'
