name: Deploy Shiny app to shinyapps.io

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up R (4.4.x)
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.4

      - name: Cache R library
        uses: actions/cache@v3
        with:
          path: ~/.R/library
          key: ${{ runner.os }}-r-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libssl-dev libcurl4-openssl-dev

      - name: Restore R packages (or install missing)
        env:
          RENV_CONFIG_REPOS_OVERRIDE: "https://packagemanager.rstudio.com/all/latest"
        run: |
          Rscript -e '
            options(repos = c(CRAN = Sys.getenv("RENV_CONFIG_REPOS_OVERRIDE")));
            if (file.exists("renv.lock")) {
              install.packages("renv"); renv::restore()
            } else {
              install.packages(c(
                "rsconnect","shiny","httr","jsonlite",
                "dplyr","text2vec","glmnet","stringdist"
              ))
            }'

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_NAME:    ${{ secrets.SHINYAPPS_NAME }}
          SHINYAPPS_TOKEN:   ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET:  ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript -e '
            rsconnect::setAccountInfo(
              name   = Sys.getenv("SHINYAPPS_ACCOUNT"),
              token  = Sys.getenv("SHINYAPPS_TOKEN"),
              secret = Sys.getenv("SHINYAPPS_SECRET")
            );
            rsconnect::deployApp(
              appName       = Sys.getenv("SHINYAPPS_NAME"),
              account       = Sys.getenv("SHINYAPPS_ACCOUNT"),
              appDir        = ".",
              appPrimaryDoc = "app.R"
            )'
